name: Publish to acceptance test on Google Cloud
on:
  push:
    branches: [ "acceptance" ]
  pull_request:
    branches: [ "acceptance" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log recent commit
        run: git log -1

      - name: Build project
        run: mvn clean package

      - name: List target directory contents
        run: ls -la target

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud storage cp target/*.jar gs://acceptance-jabber-point/'
