name: Publish Release

on:
  push:
    branches: ["main", "cloud-development"]
  pull_request:
    branches: ["main", "cloud-development"]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "19"
          cache: maven

      - name: Build the application
        run: mvn clean package

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Upload JAR to Google Cloud Storage
        run: gsutil cp target/*.jar gs://$GCP_BUCKET/
        env:
          GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
