name: acceptance upload jar to gcloud

on:
  push:
    branches: ["main", "cloud-development"]
  pull_request:
    branches: ["main", "cloud-development"]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "19"
          cache: maven

      - name: Build the application
        run: mvn clean package

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Authenticate to Google Cloud
        run: |
          printf "%s" "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-service-key.json
          cat $HOME/gcloud-service-key.json  # This will print the JSON content for debugging
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Install Google Cloud SDK
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install apt-transport-https ca-certificates -y
          sudo apt-get update && sudo apt-get install google-cloud-sdk -y

      - name: Enable Google Cloud APIs
        run: gcloud services enable storage.googleapis.com

      - name: Upload JAR to Google Cloud Storage
        run: gsutil cp target/*.jar gs://acceptance-jabber-point/
