name: Deploy to Cloud Run

on:
  push:
    branches: ["main", "cloud-development"]
  pull_request:
    branches: ["main", "cloud-development"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: "beta"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build JAR file
        run: mvn clean package

      - name: Upload JAR to Google Cloud Storage
        run: |
          gsutil cp target/*.jar gs://$GCP_BUCKET/

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy myapp \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/myapp:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "JAR_PATH=gs://$GCP_BUCKET/myapp.jar"
